# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNIDNow' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Pods for RNIDNow
  pod 'IDnowSDK'

end
